// Use any key from `fonts` below for every label from labels.js.
// `regular` is the original Inter-based app font.
window.BURA_LABEL_FONTS = {
  default: "regular",
  fonts: {
    regular: "Original app font",
    ui: "BPG SF DG",
    display: "BPG Classic Black Caps",
    square: "BPG Square 38",
    squareCaps: "BPG Square 38 Caps",
    glahoBold: "BPG Glaho Bold",
    alkSanet: "ALK Sanet",
    alkDots: "ALK Dots",
    archyEdtBold: "Archy EDT Bold",
    bpgWeb002Caps: "BPG Web 002 Caps"
  },
  preGame: {
    appTitle: "regular",
    eyebrow: "regular",
    title: "regular",
    newDeal: "regular",
    refreshGame: "regular",
    reconnect: "regular",
    setupTitle: "regular",
    playerName: "regular",
    playerNamePlaceholder: "regular",
    playerOne: "regular",
    playerTwo: "regular",
    onlineGame: "regular",
    onlineGameDetail: "regular",
    dummyOpponent: "regular",
    dummyOpponentDetail: "regular",
    easyPlay: "regular",
    easyPlayDetail: "regular",
    matchPoints: "regular",
    dealCards: "regular",
    joinWithCode: "regular",
    gameCode: "regular",
    gameCodePlaceholder: "regular",
    shareCode: "regular",
    trump: "regular",
    table: "regular",
    otherPlayer: "regular",
    currentPlayer: "regular",
    matchInformation: "regular",
    dealAgain: "regular",
    roomExpired: "regular",
    onlineUnavailable: "regular",
    onlineCreateFailed: "regular",
    onlineActionFailed: "regular",
    onlineWaiting: "regular",
    onlineRestoring: "regular",
    onlineJoined: "regular",
    invalidGameCode: "regular",
    gameNotFound: "regular",
    gameFull: "regular",
    gameJustJoined: "regular",
    reconnectNeedsCode: "regular",
    reconnecting: "regular",
    savedGameUnavailable: "regular",
    liveSyncReconnecting: "regular",
    onlineModeInstruction: "regular",
    rematchBothAgreed: "regular",
    rematchRequested: "regular",
    lobby: "regular",
    openGames: "regular",
    refreshLobby: "regular",
    lobbyEmpty: "regular",
    lobbyLoading: "regular",
    lobbyJoin: "regular",
    lobbyHosting: "regular",
    lobbyEasy: "regular",
    lobbyClassic: "regular",
    lobbyMatch: "regular"
  },
  game: {
    currentTurn: "regular",
    waiting: "regular",
    noCards: "regular",
    makingLead: "regular",
    makingAnswer: "regular",
    clear: "regular",
    claim61: "regular",
    continue: "regular",
    declareBura: "regular",
    declareMaliutka: "regular",
    increase: "regular",
    acceptOffer: "regular",
    declineOffer: "regular",
    point: "regular",
    points: "regular",
    splitDeal: "regular",
    dealSummary: "regular",
    matchSummary: "regular",
    youWon: "regular",
    youLost: "regular",
    youWonDeal: "regular",
    youLostDeal: "regular",
    pointsTaken: "regular",
    matchPoints: "regular",
    playAgain: "regular",
    rematchWaiting: "regular",
    rematchCountdown: "regular",
    rematchExpired: "regular",
    claimedTarget: "regular",
    falseClaimResult: "regular",
    declaredBuraResult: "regular",
    declinedIncreaseResult: "regular",
    tieScoreResult: "regular",
    moreCapturedPointsResult: "regular",
    noMatchPointsAwarded: "regular",
    matchPointsAwarded: "regular",
    stockCount: "regular",
    takenCards: "regular",
    dealWeight: "regular",
    matchTarget: "regular",
    themePicker: "regular",
    greenTheme: "regular",
    redTheme: "regular",
    blueTheme: "regular",
    north: "regular",
    south: "regular"
  }
};
