// Edit gameplay wording here without changing the game logic.
window.BURA_LABELS = {
  preGame: {
    appTitle: "5 Card Bura",
    eyebrow: "ეთამაშე ძმას",
    title: "5-კარტა ბურა",
    newDeal: "გადარიგება",
    refreshGame: "Refresh game",
    reconnect: "Reconnect",
    setupTitle: "თამაშის დათქმები",
    playerName: "სახელი",
    playerNamePlaceholder: "სახელი",
    playerOne: "მოთამაშე 1",
    playerTwo: "მოთამაშე 2",
    onlineGame: "თამაში ინტერნეტში",
    onlineGameDetail: "მოიწვიე მეგობარი კოდით",
    dummyOpponent: "რობოტი ოპონენტი",
    dummyOpponentDetail: "მხოლოდ კარტებს გადაგიყრის",
    easyPlay: "გამარტივებული სვლა",
    easyPlayDetail: "ინტუიტიური",
    matchPoints: "პარტიის ქულა",
    dealCards: "შექმნა",
    joinWithCode: "კოდით შესვლა",
    gameCode: "თამაშის კოდი",
    gameCodePlaceholder: "ABC123",
    shareCode: "გააზიარე კოდი",
    trump: "კოზირი",
    table: "მაგიდა",
    otherPlayer: "Other player",
    currentPlayer: "Current player",
    matchInformation: "პარტიის ინფორმაცია",
    dealAgain: "ხელახლა დარიგება",
    roomExpired: "5 წუთიანი უაქტივობის შედეგად ეს თამაში დაიხურა.",
    onlineUnavailable: "ქსელში თამაში მიუწვდომელია.",
    onlineCreateFailed: "თამაში ვერ შეიქმნა, სცადე ხელთავიდან.",
    onlineActionFailed: "თამაში ვერ გაახლდა, სცადე ხელთავიდან.",
    onlineWaiting: "ველოდებით ოპონენტს...",
    onlineRestoring: "ხელახლა დაკავშირება...",
    onlineJoined: "დაკავშირებულია {{code}}. ველოდებით შემქმნელს...",
    invalidGameCode: "6-ნიშნა კოდი.",
    gameNotFound: "თამაში ვერ მოიძებნება.",
    gameFull: "ომაგიდა სავსეა.",
    gameJustJoined: "ოპონენტი შეუერთდა თამაშს.",
    reconnectNeedsCode: "დასაკავშირებლად შეიყვანე კოდი.",
    reconnecting: "თამაშთან დაკავშირება...",
    savedGameUnavailable: "ეს თამაში მიუწვდომელია",
    liveSyncReconnecting: "სინქრონიზაცია...",
    onlineModeInstruction: "ჩაწერე თამაში კოდი ან, ახალი თამაშის შესაქმნელად, დატოვე ველი ცარიელი.",
    rematchBothAgreed: "ორივე მოთამაშე თანახმაა, თამაში დაიწყება მალე...",
    rematchRequested: "ოპონენტს უნდა რემატჩი.",
    lobby: "ლობი",
    openGames: "ღია თამაშები",
    refreshLobby: "ლობის განახლება",
    lobbyEmpty: "ღია თამაშები ჯერ არ არის.",
    lobbyLoading: "თამაშების მოძიება...",
    lobbyJoin: "შესვლა",
    lobbyHosting: "შენი თამაში",
    lobbyEasy: "მარტივი სვლა",
    lobbyClassic: "კლასიკური სვლა",
    lobbyMatch: "{{points}} ქულამდე"
  },
  game: {
    currentTurn: "სვლა",
    waiting: "ლოდინი",
    noCards: "კარტები არაა",
    makingLead: "ჩასვლა {{count}}",
    makingAnswer: "პასუხი {{selected}}/{{needed}}",
    clear: "გაუქმება",
    claim61: "ვარ",
    continue: "გაგრძელება",
    declareBura: "'ბურა'",
    declareMaliutka: "'მალიუტკა'",
    increase: "გაზრდა",
    acceptOffer: "კი",
    declineOffer: "არა",
    point: "ქულა",
    points: "ქულა",
    splitDeal: "The deal is split",
    dealSummary: "რიგების შედეგი",
    matchSummary: "პარტიის შედეგი",
    youWon: "გაიმარჯვე!",
    youLost: "დამარცხდი",
    youWonDeal: "მოიგე რიგება",
    youLostDeal: "წააგე რიგება",
    pointsTaken: "წაღებული ქულა",
    matchPoints: "პარტიის ანგარიში",
    playAgain: "მსურს კიდევ თამაში",
    rematchWaiting: "ველოდებით ოპონენტს...",
    rematchCountdown: "რემატჩის გამოცხადების დრო {{seconds}}s",
    rematchExpired: "რემატჩის გაცხადების დრო ამოიწურა.",
    claimedTarget: "{{name}} claimed {{target}} points.",
    falseClaimResult: "{{name}} made a false {{target}} claim.",
    declaredBuraResult: "{{name}} გაშალა ბურა.",
    declinedIncreaseResult: "{{responder}} დაწვა. {{offerer}} მოიგო რიგება.",
    tieScoreResult: "რიგება დასრულდა {{firstScore}}-{{secondScore}}.",
    moreCapturedPointsResult: "{{name}} დაასრულა ხელი მეტი ქულით.",
    noMatchPointsAwarded: "ქულა არ დაწერილა",
    matchPointsAwarded: "{{name}} მიიღო {{awarded}} პარტიის ქულა {{pointWord}}.",
    stockCount: "გადის {{count}}-ში",
    takenCards: "წაღებული",
    dealWeight: "რიგების წონა",
    matchTarget: "პარტია",
    themePicker: "თემა",
    greenTheme: "მწვანე თემა",
    redTheme: "წითელი თემა",
    blueTheme: "ლურჯი თემა",
    north: "",
    south: ""
  }
};

// Edit font and weight here. The numbers match the current interface weights.
// Use 400 for regular, 600 for semibold, 700 for bold, 800 for extra bold, and 900 for black.
const labelStyle = (font = "regular", weight = 400) => ({ font, weight });

window.BURA_LABEL_STYLES = {
  default: labelStyle("regular", 400),
  fonts: {
    regular: "Original app font",
    ui: "BPG SF DG",
    display: "BPG Classic Black Caps",
    square: "BPG Square 38",
    squareCaps: "BPG Square 38 Caps",
    glahoBold: "BPG Glaho Bold",
    alkSanet: "ALK Sanet",
    alkDots: "ALK Dots",
    archyEdtBold: "Archy EDT Bold",
    bpgWeb002Caps: "BPG Web 002 Caps"
  },
  preGame: {
    appTitle: labelStyle("regular", 400),
    eyebrow: labelStyle("regular", 700),
    title: labelStyle("ui", 400),
    newDeal: labelStyle("regular", 400),
    refreshGame: labelStyle("regular", 400),
    reconnect: labelStyle("regular", 800),
    setupTitle: labelStyle("regular", 700),
    playerName: labelStyle("regular", 700),
    playerNamePlaceholder: labelStyle("regular", 400),
    playerOne: labelStyle("regular", 700),
    playerTwo: labelStyle("regular", 700),
    onlineGame: labelStyle("regular", 700),
    onlineGameDetail: labelStyle("regular", 400),
    dummyOpponent: labelStyle("regular", 700),
    dummyOpponentDetail: labelStyle("regular", 400),
    easyPlay: labelStyle("regular", 700),
    easyPlayDetail: labelStyle("regular", 400),
    matchPoints: labelStyle("regular", 700),
    dealCards: labelStyle("regular", 800),
    joinWithCode: labelStyle("regular", 800),
    gameCode: labelStyle("regular", 700),
    gameCodePlaceholder: labelStyle("regular", 400),
    shareCode: labelStyle("regular", 400),
    trump: labelStyle("regular", 700),
    table: labelStyle("regular", 400),
    otherPlayer: labelStyle("regular", 400),
    currentPlayer: labelStyle("regular", 400),
    matchInformation: labelStyle("regular", 400),
    dealAgain: labelStyle("regular", 800),
    roomExpired: labelStyle("regular", 400),
    onlineUnavailable: labelStyle("regular", 400),
    onlineCreateFailed: labelStyle("regular", 400),
    onlineActionFailed: labelStyle("regular", 400),
    onlineWaiting: labelStyle("regular", 400),
    onlineRestoring: labelStyle("regular", 400),
    onlineJoined: labelStyle("regular", 400),
    invalidGameCode: labelStyle("regular", 400),
    gameNotFound: labelStyle("regular", 400),
    gameFull: labelStyle("regular", 400),
    gameJustJoined: labelStyle("regular", 400),
    reconnectNeedsCode: labelStyle("regular", 400),
    reconnecting: labelStyle("regular", 400),
    savedGameUnavailable: labelStyle("regular", 400),
    liveSyncReconnecting: labelStyle("regular", 400),
    onlineModeInstruction: labelStyle("regular", 400),
    rematchBothAgreed: labelStyle("regular", 400),
    rematchRequested: labelStyle("regular", 400),
    lobby: labelStyle("regular", 700),
    openGames: labelStyle("regular", 700),
    refreshLobby: labelStyle("regular", 400),
    lobbyEmpty: labelStyle("regular", 700),
    lobbyLoading: labelStyle("regular", 700),
    lobbyJoin: labelStyle("regular", 800),
    lobbyHosting: labelStyle("regular", 900),
    lobbyEasy: labelStyle("regular", 800),
    lobbyClassic: labelStyle("regular", 800),
    lobbyMatch: labelStyle("regular", 800)
  },
  game: {
    currentTurn: labelStyle("regular", 700),
    waiting: labelStyle("regular", 700),
    noCards: labelStyle("regular", 800),
    makingLead: labelStyle("regular", 800),
    makingAnswer: labelStyle("regular", 800),
    clear: labelStyle("regular", 800),
    claim61: labelStyle("regular", 800),
    continue: labelStyle("regular", 800),
    declareBura: labelStyle("regular", 800),
    declareMaliutka: labelStyle("regular", 800),
    increase: labelStyle("regular", 800),
    acceptOffer: labelStyle("regular", 800),
    declineOffer: labelStyle("regular", 800),
    point: labelStyle("regular", 400),
    points: labelStyle("regular", 400),
    splitDeal: labelStyle("regular", 700),
    dealSummary: labelStyle("regular", 700),
    matchSummary: labelStyle("regular", 700),
    youWon: labelStyle("regular", 700),
    youLost: labelStyle("regular", 700),
    youWonDeal: labelStyle("regular", 700),
    youLostDeal: labelStyle("regular", 700),
    pointsTaken: labelStyle("regular", 900),
    matchPoints: labelStyle("regular", 900),
    playAgain: labelStyle("regular", 800),
    rematchWaiting: labelStyle("regular", 800),
    rematchCountdown: labelStyle("regular", 900),
    rematchExpired: labelStyle("regular", 400),
    claimedTarget: labelStyle("regular", 400),
    falseClaimResult: labelStyle("regular", 400),
    declaredBuraResult: labelStyle("regular", 400),
    declinedIncreaseResult: labelStyle("regular", 400),
    tieScoreResult: labelStyle("regular", 400),
    moreCapturedPointsResult: labelStyle("regular", 400),
    noMatchPointsAwarded: labelStyle("regular", 400),
    matchPointsAwarded: labelStyle("regular", 400),
    stockCount: labelStyle("regular", 400),
    takenCards: labelStyle("regular", 900),
    dealWeight: labelStyle("regular", 900),
    matchTarget: labelStyle("regular", 900),
    themePicker: labelStyle("regular", 400),
    greenTheme: labelStyle("regular", 400),
    redTheme: labelStyle("regular", 400),
    blueTheme: labelStyle("regular", 400),
    north: labelStyle("regular", 400),
    south: labelStyle("regular", 400)
  }
};
