// Edit gameplay wording here without changing the game logic.
window.BURA_LABELS = {
  preGame: {
    eyebrow: "ეთამაშე ძმას",
    title: "5-კარტა ბურა",
    newDeal: "new deal",
    refreshGame: "Refresh game",
    reconnect: "Reconnect",
    targetKicker: "Target locked at 61",
    setupTitle: "თამაშის დათქმები",
    playerNamePlaceholder: "მოთამაშე",
    playerOne: "მოთამაშე 1",
    playerTwo: "მოთამაშე 2",
    dummyOpponent: "Development mode: dummy opponent",
    easyPlay: "გამარტივებული სვლა",
    easyPlayDetail: "ინტუიტიური",
    matchPoints: "პარტიის ქულა",
    dealCards: "შექმნა",
    trump: "კოზირი",
    table: "Table",
    otherPlayer: "Other player",
    currentPlayer: "Current player",
    dealFinished: "Deal finished",
    winner: "Winner",
    dealAgain: "Deal again",
    roomExpired: "This game closed after five minutes of inactivity."
  },
  game: {
    currentTurn: "სვლა",
    waiting: "ლოდინი",
    lead: "ჩასვლა",
    answer: "სვლა",
    noCards: "No cards",
    turn: "Turn",
    makingMove: "Making move",
    trickComplete: "Trick complete",
    cardsRevealed: "Cards revealed",
    nextTurn: "The next turn starts in a moment.",
    dealComplete: "Deal complete",
    tieDeal: "ფრე",
    dealingNext: "Dealing the next hand...",
    newTable: "New local table",
    dummyPlaying: "Dummy opponent is playing",
    dummyDetail: "The dummy chooses the first legal card(s).",
    dealOffer: "Deal offer",
    maliutkaDetail: "{{name}} has Maliutka",
    passTo: "Pass to {{name}}",
    leadTitle: "{{name}}, lead the trick",
    answerTitle: "{{name}}, answer the lead",
    leadDetail: "{{name}} has the lead.",
    answerDetail: "{{name}} answers {{count}} {{cardWord}}.",
    chooseCards: "Choose cards from your hand.",
    chooseAtLeast: "Choose at least one card to lead.",
    tooManyLead: "You cannot lead more cards than your opponent can answer.",
    sameSuit: "Lead cards must all be the same suit.",
    exactCards: "Choose exactly {{needed}} {{cardWord}}.",
    makingLead: "Lead {{count}}",
    makingAnswer: "Answer {{selected}}/{{needed}}",
    clear: "Clear",
    claim61: "Claim 61",
    continue: "Continue",
    declareBura: "Declare Bura",
    declareMaliutka: "Declare Maliutka",
    increase: "Increase",
    buraDetail: "{{name}} has Bura",
    buraPrompt: "Declare it before the next turn.",
    offerTitle: "{{name}} offers +1",
    offerDetail: "Accept to make this deal worth {{weight}} match {{pointWord}}, or decline to concede it.",
    reviewOffer: "Review offer",
    acceptOffer: "Accept +1",
    declineOffer: "Decline",
    scorePoints: "{{count}} selected, {{points}} card {{pointWord}}.",
    point: "point",
    points: "points",
    card: "card",
    cards: "cards",
    falseClaim: "{{name}} has {{score}}. A false 61 claim loses the deal. Claim anyway?",
    splitDeal: "The deal is split",
    wonDeal: "{{name}} won the deal",
    wonGame: "{{name}} won",
    dealSummary: "Deal summary",
    matchSummary: "Match complete",
    youWon: "You won!",
    youLost: "You lost",
    youWonDeal: "You won the deal",
    youLostDeal: "You lost the deal",
    pointsTaken: "points taken",
    matchPoints: "match points",
    playAgain: "I want to play again",
    rematchWaiting: "Waiting for the other player...",
    rematchCountdown: "New game decision closes in {{seconds}}s",
    rematchExpired: "The rematch window expired.",
    finalScore: "Match score: {{firstName}} {{firstMatch}}, {{secondName}} {{secondMatch}}. Final deal score: {{firstScore}}-{{secondScore}}.",
    stockCount: "{{count}} in stock",
    takenCards: "cards taken",
    match: "Match",
    dealWeight: "Deal weight",
    matchTarget: "Match target",
    north: "NORTH",
    south: "SOUTH"
  }
};
