// Edit gameplay wording here without changing the game logic.
window.BURA_LABELS = {
  preGame: {
    appTitle: "5 Card Bura",
    eyebrow: "ეთამაშე ძმას",
    title: "5-კარტა ბურა",
    newDeal: "new deal",
    refreshGame: "Refresh game",
    reconnect: "Reconnect",
    targetKicker: "Target locked at 61",
    setupTitle: "თამაშის დათქმები",
    playerName: "Player name",
    playerNamePlaceholder: "მოთამაშე",
    playerOne: "მოთამაშე 1",
    playerTwo: "მოთამაშე 2",
    onlineGame: "Online game",
    onlineGameDetail: "Invite another player with a code",
    dummyOpponent: "Dummy opponent",
    dummyOpponentDetail: "Play against the development opponent",
    easyPlay: "გამარტივებული სვლა",
    easyPlayDetail: "ინტუიტიური",
    matchPoints: "პარტიის ქულა",
    dealCards: "შექმნა",
    joinWithCode: "კოდით შესვლა",
    gameCode: "Game code",
    gameCodePlaceholder: "ABC123",
    shareCode: "Share this code",
    trump: "კოზირი",
    table: "Table",
    otherPlayer: "Other player",
    currentPlayer: "Current player",
    matchInformation: "Match information",
    dealFinished: "Deal finished",
    winner: "Winner",
    dealAgain: "Deal again",
    roomExpired: "This game closed after five minutes of inactivity.",
    onlineUnavailable: "Online mode is unavailable right now.",
    onlineCreateFailed: "Could not create the game. Please try again.",
    onlineActionFailed: "Could not update the game. Please try again.",
    onlineWaiting: "Waiting for the other player...",
    onlineRestoring: "Restoring the game...",
    onlineJoined: "Joined {{code}}. Waiting for the host to deal...",
    invalidGameCode: "Enter the six-character game code.",
    gameNotFound: "Game not found.",
    gameFull: "That game already has an opponent.",
    gameJustJoined: "That game was just joined by someone else.",
    reconnectNeedsCode: "Enter a game code to reconnect.",
    reconnecting: "Reconnecting to the game...",
    savedGameUnavailable: "This saved game is no longer available.",
    liveSyncReconnecting: "Live sync is reconnecting...",
    onlineModeInstruction: "Leave the code empty to create a game, or enter a code to join.",
    rematchBothAgreed: "Both players agreed. Starting again...",
    rematchRequested: "The other player wants a rematch."
  },
  game: {
    currentTurn: "სვლა",
    waiting: "ლოდინი",
    lead: "ჩასვლა",
    answer: "სვლა",
    noCards: "No cards",
    turn: "Turn",
    makingMove: "Making move",
    trickComplete: "Trick complete",
    cardsRevealed: "Cards revealed",
    nextTurn: "The next turn starts in a moment.",
    dealComplete: "Deal complete",
    tieDeal: "ფრე",
    dealingNext: "Dealing the next hand...",
    newTable: "New local table",
    dummyPlaying: "Dummy opponent is playing",
    dummyDetail: "The dummy chooses the first legal card(s).",
    dealOffer: "Deal offer",
    maliutkaDetail: "{{name}} has Maliutka",
    passTo: "Pass to {{name}}",
    leadTitle: "{{name}}, lead the trick",
    answerTitle: "{{name}}, answer the lead",
    leadDetail: "{{name}} has the lead.",
    answerDetail: "{{name}} answers {{count}} {{cardWord}}.",
    chooseCards: "Choose cards from your hand.",
    chooseAtLeast: "Choose at least one card to lead.",
    tooManyLead: "You cannot lead more cards than your opponent can answer.",
    sameSuit: "Lead cards must all be the same suit.",
    exactCards: "Choose exactly {{needed}} {{cardWord}}.",
    makingLead: "Lead {{count}}",
    makingAnswer: "Answer {{selected}}/{{needed}}",
    clear: "Clear",
    claim61: "Claim 61",
    continue: "Continue",
    declareBura: "Declare Bura",
    declareMaliutka: "Declare Maliutka",
    increase: "Increase",
    buraDetail: "{{name}} has Bura",
    buraPrompt: "Declare it before the next turn.",
    offerTitle: "{{name}} offers +1",
    offerDetail: "Accept to make this deal worth {{weight}} match {{pointWord}}, or decline to concede it.",
    reviewOffer: "Review offer",
    acceptOffer: "Accept +1",
    declineOffer: "Decline",
    scorePoints: "{{count}} selected, {{points}} card {{pointWord}}.",
    point: "point",
    points: "points",
    card: "card",
    cards: "cards",
    falseClaim: "{{name}} has {{score}}. A false 61 claim loses the deal. Claim anyway?",
    splitDeal: "The deal is split",
    wonDeal: "{{name}} won the deal",
    wonGame: "{{name}} won",
    dealSummary: "Deal summary",
    matchSummary: "Match complete",
    youWon: "You won!",
    youLost: "You lost",
    youWonDeal: "You won the deal",
    youLostDeal: "You lost the deal",
    pointsTaken: "points taken",
    matchPoints: "match points",
    playAgain: "I want to play again",
    rematchWaiting: "Waiting for the other player...",
    rematchCountdown: "New game decision closes in {{seconds}}s",
    rematchExpired: "The rematch window expired.",
    claimedTarget: "{{name}} claimed {{target}} points.",
    falseClaimResult: "{{name}} made a false {{target}} claim.",
    declaredBuraResult: "{{name}} declared Bura with all five trumps.",
    declinedIncreaseResult: "{{responder}} declined the raise. {{offerer}} wins the deal.",
    tieScoreResult: "The deal ended {{firstScore}}-{{secondScore}}.",
    moreCapturedPointsResult: "{{name}} finished with more captured points.",
    noMatchPointsAwarded: "No match points were awarded.",
    matchPointsAwarded: "{{name}} received {{awarded}} match {{pointWord}}.",
    finalScore: "Match score: {{firstName}} {{firstMatch}}, {{secondName}} {{secondMatch}}. Final deal score: {{firstScore}}-{{secondScore}}.",
    stockCount: "{{count}} in stock",
    takenCards: "cards taken",
    match: "Match",
    dealWeight: "Deal weight",
    matchTarget: "Match target",
    north: "NORTH",
    south: "SOUTH"
  }
};
