// Use any key from `fonts` below for every label from labels.js.
// `regular` is the original Inter-based app font.
window.BURA_LABEL_FONTS = {
  default: "ui",
  fonts: {
    regular: "Original app font",
    ui: "BPG SF DG",
    display: "BPG Classic Black Caps",
    square: "BPG Square 38",
    squareCaps: "BPG Square 38 Caps",
    glahoBold: "BPG Glaho Bold"
  },
  preGame: {
    appTitle: "ui",
    eyebrow: "ui",
    title: "ui",
    newDeal: "ui",
    refreshGame: "ui",
    reconnect: "ui",
    setupTitle: "ui",
    playerName: "ui",
    playerNamePlaceholder: "ui",
    playerOne: "ui",
    playerTwo: "ui",
    onlineGame: "ui",
    onlineGameDetail: "ui",
    dummyOpponent: "ui",
    dummyOpponentDetail: "ui",
    easyPlay: "ui",
    easyPlayDetail: "ui",
    matchPoints: "ui",
    dealCards: "ui",
    joinWithCode: "ui",
    gameCode: "ui",
    gameCodePlaceholder: "ui",
    shareCode: "ui",
    trump: "ui",
    table: "ui",
    otherPlayer: "ui",
    currentPlayer: "ui",
    matchInformation: "ui",
    dealAgain: "ui",
    roomExpired: "ui",
    onlineUnavailable: "ui",
    onlineCreateFailed: "ui",
    onlineActionFailed: "ui",
    onlineWaiting: "ui",
    onlineRestoring: "ui",
    onlineJoined: "ui",
    invalidGameCode: "ui",
    gameNotFound: "ui",
    gameFull: "ui",
    gameJustJoined: "ui",
    reconnectNeedsCode: "ui",
    reconnecting: "ui",
    savedGameUnavailable: "ui",
    liveSyncReconnecting: "ui",
    onlineModeInstruction: "ui",
    rematchBothAgreed: "ui",
    rematchRequested: "ui",
    lobby: "ui",
    openGames: "display",
    refreshLobby: "ui",
    lobbyEmpty: "ui",
    lobbyLoading: "ui",
    lobbyJoin: "ui",
    lobbyHosting: "ui",
    lobbyEasy: "ui",
    lobbyClassic: "ui",
    lobbyMatch: "ui"
  },
  game: {
    currentTurn: "display",
    waiting: "display",
    noCards: "ui",
    makingLead: "ui",
    makingAnswer: "ui",
    clear: "ui",
    claim61: "ui",
    continue: "ui",
    declareBura: "ui",
    declareMaliutka: "ui",
    increase: "ui",
    acceptOffer: "ui",
    declineOffer: "ui",
    point: "ui",
    points: "ui",
    dealSummary: "display",
    matchSummary: "display",
    splitDeal: "display",
    youWon: "display",
    youLost: "display",
    youWonDeal: "display",
    youLostDeal: "display",
    pointsTaken: "ui",
    matchPoints: "ui",
    playAgain: "ui",
    rematchWaiting: "ui",
    rematchCountdown: "ui",
    rematchExpired: "ui",
    claimedTarget: "ui",
    falseClaimResult: "ui",
    declaredBuraResult: "ui",
    declinedIncreaseResult: "ui",
    tieScoreResult: "ui",
    moreCapturedPointsResult: "ui",
    noMatchPointsAwarded: "ui",
    matchPointsAwarded: "ui",
    stockCount: "ui",
    takenCards: "ui",
    dealWeight: "ui",
    matchTarget: "ui",
    themePicker: "ui",
    greenTheme: "ui",
    redTheme: "ui",
    blueTheme: "ui",
    north: "ui",
    south: "ui"
  }
};
