// English label map. Edit the text values here without changing the app code.
window.BURA_LABELS_EN = {
  preGame: {
    appTitle: "5-Card Bura",
    eyebrow: "Play with broda",
    title: "5-Card Bura",
    settings: "Settings",
    setupTitle: "Game setup",
    accountPanel: "Account",
    accountTitle: "Sign in",
    accountGreeting: "Gamarjoba, {{name}}.",
    accountGuest: "Guest",
    accountUser: "User",
    accountGuestNote: "Sign in to save your profile.",
    accountUserNote: "",
    accountGoogle: "Continue with Google",
    accountFacebook: "Continue with Facebook",
    accountCoins: "Coins",
    accountRank: "Rank",
    accountKarma: "Karma",
    accountMatches: "Completed",
    accountMatchHistory: "Last 5 matches",
    accountMatchHistoryEmpty: "No completed matches yet.",
    accountMatchUnknownOpponent: "Unknown opponent",
    accountMatchWin: "Won",
    accountMatchLoss: "Lost",
    accountAchievements: "Achievements",
    accountAchievementMatches: "{{count}} completed matches",
    accountAchievementStreak: "{{count}} wins in a row",
    accountAchievementCoins: "{{count}} coins",
    accountAchievementBura: "{{count}} Bura declarations",
    accountAchievementReliability: "95% karma",
    accountAchievementFounder: "Founder",
    accountAchievementFirstHundred: "First 100 registered users",
    accountProfile: "User profile",
    accountEditName: "Change player name",
    accountCopyId: "Copy user ID",
    accountCustomizeEmblem: "Customize emblem",
    accountEmblemRank: "Rank",
    accountEmblemSuit: "Suit",
    accountEmblemFrame: "Frame",
    accountSuitClubs: "Clubs ♣",
    accountSuitSpades: "Spades ♠",
    accountSuitDiamonds: "Diamonds ♦",
    accountSuitHearts: "Hearts ♥",
    accountFrameGold: "Gold",
    accountFrameWhite: "White",
    accountFrameGreen: "Green",
    accountEmblemSaved: "Emblem saved.",
    accountIdCopied: "ID copied.",
    accountIdCopyFailed: "Could not copy ID.",
    accountRankNewcomer: "Newcomer",
    accountRankBronze: "Bronze",
    accountRankSilver: "Silver",
    accountRankGold: "Gold",
    accountRankMaster: "Master",
    accountPlayerName: "Player name",
    accountSaveName: "Save",
    accountNameSaved: "Name saved.",
    accountNameRequired: "Enter a name.",
    accountNameSaveFailed: "Could not save the name. Try again.",
    accountSignOut: "Sign out",
    closeAccountPanel: "Close account",
    accountSettings: "Settings",
    closeAccountSettings: "Close settings",
    language: "Language",
    languageGeorgian: "GEO",
    languageEnglish: "ENG",
    defaultTheme: "Default theme",
    cardDeck: "Card deck",
    deckClassic: "Deck 1",
    deckMobile: "Deck 2",
    inviteJoinTitle: "Join game",
    inviteContinueGuest: "Continue as guest",
    playerNamePlaceholder: "Name",
    playerOne: "Player 1",
    playerTwo: "Player 2",
    onlineGame: "Online game",
    onlineGameDetail: "Invite a friend with a link",
    dummyOpponent: "Computer opponent",
    dummyOpponentDetail: "A simple practice opponent",
    easyPlay: "Easy play",
    easyPlayDetail: "Guided controls",
    matchPoints: "Match points",
    freeGame: "Free",
    lobbyFreeGame: "Free game",
    dealCards: "Create",
    joinWithCode: "Join with code",
    gameCode: "Game code",
    gameCodePlaceholder: "ABC123",
    trump: "Trump",
    table: "Table",
    otherPlayer: "Other player",
    currentPlayer: "Current player",
    matchInformation: "Match information",
    dealAgain: "Deal again",
    roomExpired: "This game closed after 5 minutes of inactivity.",
    onlineUnavailable: "Online play is unavailable.",
    onlineCreateFailed: "Could not create the game. Try again.",
    insufficientCoins: "Could not create the game.",
    onlineActionFailed: "Could not update the game. Try again.",
    hostRoomLimit: "You can create up to three games at once.",
    onlineWaiting: "Waiting for an opponent...",
    onlineRestoring: "Reconnecting...",
    onlineJoined: "Joined {{code}}. Waiting for the host...",
    invalidGameCode: "Use a 6-character code.",
    gameNotFound: "Game not found.",
    gameFull: "The table is full.",
    gameJustJoined: "Your opponent joined the game.",
    reconnectNeedsCode: "Enter a code to reconnect.",
    reconnecting: "Connecting to the game...",
    savedGameUnavailable: "This game is unavailable.",
    liveSyncReconnecting: "Synchronizing...",
    onlineModeInstruction: "Create a game and share its link.",
    rematchBothAgreed: "Both players agreed. The game will start shortly...",
    rematchRequested: "Your opponent wants a rematch.",
    openGames: "Games",
    refreshLobby: "Refresh lobby",
    lobbyEmpty: "There are no games yet.",
    lobbyLoading: "Finding games...",
    lobbyJoin: "Join",
    lobbyCurrent: "Current game",
    lobbyCancel: "Cancel",
    copyGameCode: "Copy code {{code}}",
    gameCodeCopied: "Code copied.",
    copyGameLink: "Copy link",
    gameLinkCopied: "Link copied.",
    lobbyFilter: "Game filter",
    lobbyOpen: "Open",
    lobbyActive: "Active",
    lobbyPlaying: "In progress",
    lobbyMatch: "To {{points}} points"
  },
  game: {
    makingLead: "Lead {{count}}",
    makingAnswer: "Reply {{selected}}/{{needed}}",
    clear: "Clear",
    claim61: "I have it",
    continue: "Continue",
    maliutkaMove: "Move",
    declareBura: "Bura",
    declareMaliutka: "Maliutka",
    increase: "Raise",
    increaseToTwo: "Davi",
    increaseToThree: "Se",
    increaseToFour: "Chari",
    increaseToFive: "Panji",
    increaseToSix: "Shashi",
    acceptOffer: "Yes",
    declineOffer: "No",
    splitDeal: "Tie",
    matchSummary: "Match result",
    youWon: "You won the match!",
    youLost: "You lost the match.",
    matchTimeoutWinner: "Opponent ran out of time",
    exitMatch: "Back to menu",
    playAgain: "Play again",
    rematchWaiting: "Waiting for opponent...",
    rematchCountdown: "Rematch expires in {{seconds}} s.",
    rematchExpired: "The rematch request expired.",
    claimedTargetWinner: "You claimed the target and had it.",
    claimedTargetLoser: "Opponent claimed the target and had it.",
    falseClaimResultWinner: "Opponent claimed the target but did not have it.",
    falseClaimResultLoser: "You claimed the target but did not have it.",
    declaredBuraResultWinner: "You declared Bura!",
    declaredBuraResultLoser: "Opponent declared Bura!",
    declinedIncreaseResultWinner: "Opponent declined.",
    declinedIncreaseResultLoser: "You declined.",
    tieScoreResult: "Tie,",
    moreCapturedPointsResultWinner: "You finished the deal with more points.",
    moreCapturedPointsResultLoser: "Opponent finished the deal with more points.",
    stockCount: "{{count}} remaining",
    takenCards: "Taken",
    capturedScoreComparison: "{{player}} : {{opponent}}",
    dealWeight: "Weight",
    matchTarget: "Match",
    themePicker: "Theme",
    greenTheme: "Green theme",
    redTheme: "Red theme",
    blueTheme: "Blue theme",
    north: "",
    south: ""
  }
};
