-- Future online-room storage for 5 Card Bura.
-- The current prototype is local pass-and-play; this schema stores room state
-- as JSON so the existing game reducer can be synced through Supabase next.

create table if not exists public.bura_games (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (char_length(code) = 5),
  target_points smallint not null default 61 check (target_points = 61),
  status text not null default 'waiting' check (status in ('waiting', 'playing', 'finished')),
  state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bura_players (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references public.bura_games(id) on delete cascade,
  player_slot smallint not null check (player_slot in (1, 2)),
  display_name text not null default 'Player',
  joined_at timestamptz not null default now(),
  unique (game_id, player_slot)
);

create table if not exists public.bura_moves (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.bura_games(id) on delete cascade,
  player_slot smallint not null check (player_slot in (1, 2)),
  action text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.bura_games enable row level security;
alter table public.bura_players enable row level security;
alter table public.bura_moves enable row level security;

create policy "public bura game access" on public.bura_games for all to anon using (true) with check (true);
create policy "public bura player access" on public.bura_players for all to anon using (true) with check (true);
create policy "public bura move access" on public.bura_moves for all to anon using (true) with check (true);

alter publication supabase_realtime add table public.bura_games;
alter publication supabase_realtime add table public.bura_players;
alter publication supabase_realtime add table public.bura_moves;
