-- Durable compact action stream for the v2.121b event-sync experiment.
create table if not exists public.bura_room_actions (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.bura_rooms(id) on delete cascade,
  kind text not null check (kind in ('request', 'resolved', 'rejected')),
  action jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.bura_room_actions enable row level security;

drop policy if exists "bura room actions readable" on public.bura_room_actions;
create policy "bura room actions readable"
  on public.bura_room_actions for select to anon, authenticated using (true);

drop policy if exists "bura room actions insertable" on public.bura_room_actions;
create policy "bura room actions insertable"
  on public.bura_room_actions for insert to anon, authenticated with check (true);

create index if not exists bura_room_actions_room_id_id_idx
  on public.bura_room_actions (room_id, id);

do $$
begin
  alter publication supabase_realtime add table public.bura_room_actions;
exception when duplicate_object then null;
end $$;
