-- Applied to project jchwubvlaexheequcvim on 2026-08-08.
-- Keeps an online room reconnectable for five minutes after its last update.
create extension if not exists pg_cron with schema pg_catalog;

grant usage on schema cron to postgres;
grant all privileges on all tables in schema cron to postgres;

alter table public.bura_rooms
  add column if not exists expires_at timestamptz;

update public.bura_rooms
set expires_at = coalesce(updated_at, created_at, now()) + interval '5 minutes'
where expires_at is null;

alter table public.bura_rooms
  alter column expires_at set default (now() + interval '5 minutes'),
  alter column expires_at set not null;

alter table public.bura_rooms
  drop constraint if exists bura_rooms_status_check;

alter table public.bura_rooms
  add constraint bura_rooms_status_check
  check (status in ('waiting', 'playing', 'finished', 'rematch_waiting', 'expired'));

create index if not exists bura_rooms_expiry_open_idx
  on public.bura_rooms (expires_at)
  where status <> 'expired';

create or replace function public.set_bura_rooms_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

alter function public.touch_bura_rooms_updated_at() set search_path to '';

create table if not exists public.bura_room_actions (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.bura_rooms(id) on delete cascade,
  kind text not null check (kind in ('request', 'resolved', 'rejected')),
  action jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.bura_room_actions enable row level security;

drop policy if exists "bura room actions readable" on public.bura_room_actions;
create policy "bura room actions readable"
  on public.bura_room_actions for select to anon, authenticated using (true);

drop policy if exists "bura room actions insertable" on public.bura_room_actions;
create policy "bura room actions insertable"
  on public.bura_room_actions for insert to anon, authenticated with check (true);

create index if not exists bura_room_actions_room_id_id_idx
  on public.bura_room_actions (room_id, id);

do $$
begin
  alter publication supabase_realtime add table public.bura_room_actions;
exception when duplicate_object then null;
end $$;

select cron.schedule(
  'expire-inactive-bura-rooms',
  '* * * * *',
  $job$
    update public.bura_rooms
    set status = 'expired', action = null
    where status <> 'expired'
      and expires_at <= now();
  $job$
);

create index if not exists bura_rooms_cleanup_idx
  on public.bura_rooms (updated_at)
  where status in ('finished', 'expired');

do $$
declare
  scheduled_job_id bigint;
begin
  select jobid into scheduled_job_id
  from cron.job
  where jobname = 'delete-old-bura-rooms'
  limit 1;

  if scheduled_job_id is not null then
    perform cron.unschedule(scheduled_job_id);
  end if;
end $$;

select cron.schedule(
  'delete-old-bura-rooms',
  '*/5 * * * *',
  $job$
    delete from public.bura_rooms
    where status in ('finished', 'expired')
      and updated_at < now() - interval '1 hour';
  $job$
);
